library(Seurat)

cat("========== UNTREATED final object ==========\n")
seu_u <- readRDS("/shared/DATA_GSE233866/seurat_GSE233866_SNc_VTA.rds")
cat("Total cells in final object (post-QC, post-cluster):", ncol(seu_u), "\n")
cat("cell_type breakdown:\n")
print(table(seu_u$cell_type))
cat("\nPer-animal cell_type breakdown:\n")
print(table(seu_u$sample_id, seu_u$cell_type))
cat("\nregion breakdown (within DA neurons; NA = ambiguous/excluded):\n")
print(table(seu_u$region, useNA = "always"))
cat("\nPer-animal region breakdown:\n")
print(table(seu_u$sample_id, seu_u$region, useNA = "always"))

cat("\n\n========== LESION ARM final object ==========\n")
seu_l <- readRDS("/shared/DATA_GSE233866/seurat_lesion_intact_SNc_VTA.rds")
cat("Total cells in final object (post-QC, post-cluster):", ncol(seu_l), "\n")
cat("cell_type x condition breakdown:\n")
print(table(seu_l$cell_type, seu_l$condition))
cat("\nregion x condition breakdown (NA = ambiguous/excluded):\n")
print(table(seu_l$region, seu_l$condition, useNA = "always"))
cat("\nPer-animal x condition, DA neurons only:\n")
da_l <- seu_l[, seu_l$cell_type == "Dopaminergic Neurons"]
print(table(da_l$sample_id, da_l$condition))
cat("\nPer-animal x condition x region, DA neurons only:\n")
print(table(da_l$sample_id, da_l$condition, da_l$region, useNA = "always"))

cat("\nDIAGNOSTIC COMPLETE\n")
